### ISSUE TITLE
Binance module 

### ISSUE THREAD

**Issue by mrhouzlane** [DGabri/manage_binance_orderbook#1]
I am having this error : ``` ModuleNotFoundError: No module named 'binance.websocket' ``` 

Is the notebook still working for you ? 

I tried many ways to install binance for python .. 

I have also changed it to this : from binance import Client, ThreadedWebsocketManager, ThreadedDepthCacheManager

**Comment by DGabri** [comment]
Hi, thanks for using my script! 
I updated the readme, pleas install the required package
